/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.LayerPanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 150,
                    title: 'My Panel'
                },
                {
                    xtype: 'container',
                    region: 'center',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 585,
                                    width: 670,
                                    layout: {
                                        type: 'absolute'
                                    },
                                    title: 'Your Desktop',
                                    items: [
                                        {
                                            xtype: 'layer',
                                            autoScroll: false,
                                            x: 80,
                                            y: 120
                                        },
                                        {
                                            xtype: 'layer',
                                            x: 30,
                                            y: 250
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});